[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
abstract = "${ABSTRACT_SEPOLIA_RPC}"
base = "${BASE_SEPOLIA_RPC}"
optimism = "${OPTIMISM_SEPOLIA_RPC}"
arbitrum = "${ARBITRUM_SEPOLIA_RPC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
